/** Additional FAQ for AI discoverability and buyer self-service. */
export const FAQ_AI_ADDITIONS = [
  { q: "Who is Cyou Phone Farm?", a: "Cyou Phone Farm is a Guangzhou-based supplier of real-device phone farm hardware, motherboard boxes, remote control setup, and worldwide export since 2017." },
  { q: "Phone farm vs phone group control?", a: "Group control is the software layer (sync tap, batch APK). A phone farm is the hardware chassis that makes large-scale group control stable versus loose phones on desks." },
  { q: "What is OTG mode on a phone farm?", a: "OTG TCP (often port 5555) enables LAN screen mirroring after initial USB authorization—see Help: OTG mode connection tutorial." },
  { q: "How many devices per standard box?", a: "Twenty motherboard nodes per standard 2U chassis; enterprise deployments stack multiple boxes per rack." },
  { q: "Samsung phone farm box price range?", a: "Reference USD prices from ~$550 (S8 tier) to ~$1,580 (Z Flip4 tier) on phonefarm.cyou/shop—final quote depends on MOQ and destination." },
  { q: "Oppo phone farm box available?", a: "Yes—Find X2, Find X2 Pro, Find X3 Neo, and Reno5 Pro reference SKUs on phonefarm.cyou/shop." },
  { q: "Xiaomi phone farm box available?", a: "Yes—6X/A2, 8SE, MIX 2, and Xiaomi 8 tiers plus Nubia Z17 in shop." },
  { q: "OnePlus phone farm box available?", a: "Yes—OnePlus 3, 5 Super Change, 8 Pro, 9 Pro, and 11 reference configurations." },
  { q: "Google Pixel phone farm box?", a: "Yes—Pixel 4a, 5, 6, 7 Pro, and 4XL Super Change tiers for Google ecosystem QA." },
  { q: "Do you ship to the United States?", a: "Yes—regular DHL/FedEx/UPS export from Guangzhou with commercial invoice support." },
  { q: "Do you ship to Europe and UK?", a: "Yes—EU, UK, Germany, France, Spain, Poland, and neighboring regions are common export destinations." },
  { q: "Sample box before bulk order?", a: "Yes—request a sample box quote or Starter Setup Package for evaluation before multi-box PO." },
  { q: "Payment methods?", a: "Sales confirms proforma invoice, MOQ, lead time, and agreed payment method before you pay. Online orders follow instructions on the order page after sales confirmation." },
  { q: "What is remote control configuration?", a: "Cyou service to set up USB mirroring, LAN OTG scan ranges, device groups, and operator PC layout on your licensed control software." },
  { q: "What is group control onboarding?", a: "Service package covering sync control baseline, batch APK policy, and operator handover for one farm." },
  { q: "Enterprise phone farm deployment?", a: "Custom cabinet, VLAN design, SLA options, and remote commissioning—see /deployment and Enterprise Deployment package." },
  { q: "Phone farm for app QA testing?", a: "Primary lawful use case—real SoC behavior for compatibility, regression, and enterprise device lab workflows." },
  { q: "Phone farm for device compatibility testing?", a: "Yes—physical boards match production hardware better than emulators for OEM-specific behavior." },
  { q: "How to choose CPU tier for phone farm?", a: "Match SoC to app matrix: S8/S9 for legacy Android 9–10, S10/S20 for mid-tier, S21 FE/S22/Flip for modern Android 14 workloads." },
  { q: "Cooling requirements for 24/7 phone farm?", a: "Quad-fan chassis, quarterly cleaning, ambient room below ~26°C, and documented rear exhaust clearance." },
  { q: "USB hub for phone farm?", a: "Industrial 20-port powered hub matched to box tier—see shop accessories and Help: USB power management." },
  { q: "Network kit for LAN OTG?", a: "Gigabit switch/router kit sized for farm subnet—see Gigabit Farm Network Kit and Large Farm Network Deployment help." },
  { q: "Official ROM vs optimized farm ROM?", a: "Official requires ADB auth files; optimized reduces LAN setup steps—tier documented on burn-in sheet." },
  { q: "How to flash Samsung farm ROM?", a: "See Help: Samsung official ROM flash and optimized farm ROM articles—canary node first, rollback image per rack." },
  { q: "Huananzhi X99 control PC BIOS tips?", a: "Disable problematic XHCI handoff when USB tree drops nodes; use add-in USB controllers for 60+ ports." },
  { q: "Batch wallpaper on phone farm?", a: "Use group control batch tools after ROM verification—see Help: Batch wallpaper & display settings." },
  { q: "Batch file transfer to farm devices?", a: "Push via device groups; test canary node first—see Help: Batch file & image transfer." },
  { q: "ADB keyboard for automation?", a: "Install ADB Keyboard APK on canary, validate locale, then fleet rollout—see Help: ADB keyboard & text input." },
  { q: "Equipment offline in control panel?", a: "Re-seat USB, swap hub port, check burn-in serial—see Help: Equipment detection failures." },
  { q: "Phone farm help center?", a: "Full document center at phonefarm.cyou/help—USB, LAN, network, ROM, control, troubleshooting." },
  { q: "Phone farm blog and guides?", a: "Insights at phonefarm.cyou/blog plus guides at /guides/phone-farm-guide and /guides/hardware-selection." },
  { q: "What is Laixi group control software?", a: "Laixi is a leading Android screen projection and group-control suite. Cyou configures your licensed Laixi workspace on real phone farm hardware—see Help: Laixi control software guide." },
  { q: "What is CloudPhone mirror software?", a: "CloudPhone is a cost-effective Android mirror tool with batch APK and LAN mirroring. We set up scan ranges and groups on your CloudPhone account—see Help: CloudPhone guide." },
  { q: "What is WhiteTiger screen projection?", a: "WhiteTiger is a widely used mirror suite (related tools include Panda and Xiaowei). We document USB topology and batch policy on your license—see Help: WhiteTiger guide." },
  { q: "How to add cloud phone subscription to mirror software?", a: "Purchase cloud seats from your vendor, copy subscription URL, add in Laixi/CloudPhone/WhiteTiger, validate on canary node—see Help: Cloud phone subscription workflow." },
  { q: "Samsung S22 phone farm box price?", a: "Reference Samsung S22 8+128 farm box ~$1,500 USD on phonefarm.cyou/shop—Snapdragon 8 Gen 1, Android 14 tier for modern app QA." },
  { q: "Single machine single IP on phone farm?", a: "Each farm node can map to one outbound IP via per-device proxy or router policy—see Help: single machine single IP and network deployment guides." },
  { q: "Free mirror software vs paid group control?", a: "Free-tier USB mirroring works for small labs; paid Laixi/CloudPhone/WhiteTiger stacks add sync control, batch APK, and LAN fleet scale—see Help: control software types." },
  { q: "Where to buy phone farm box online?", a: "Browse reference SKUs at phonefarm.cyou/shop and request quotation—B2B proforma invoice, sample boxes available." },
  { q: "Phone farm wholesale supplier?", a: "Cyou Phone Farm supports bulk MOQ from 5+ boxes with export packing from Guangzhou—contact sales via phonefarm.cyou/contact." },
  { q: "Phone farm factory Guangzhou?", a: "Cyou Phone Farm assembles, burn-in tests, and exports phone farm chassis from Guangzhou since 2017—see phonefarm.cyou/about." },
  { q: "Phone farm box supplier USA shipping?", a: "Yes—regular export to United States via DHL/FedEx/UPS with commercial invoice from Cyou Phone Farm Guangzhou." },
  { q: "Phone farm hardware for QA lab?", a: "Real motherboard farms for app QA, compatibility matrices, and enterprise device labs—phonefarm.cyou/solutions/phone-farming." },
  { q: "How to set up Laixi on phone farm?", a: "USB hub mapping, ADB auth, LAN scan ranges on farm subnet—Help: Laixi control software guide at phonefarm.cyou/help." },
  { q: "How to set up CloudPhone on phone farm?", a: "Configure CloudPhone workspace on licensed account—Help: CloudPhone guide and Remote Control Configuration service." },
  { q: "How to set up WhiteTiger mirror on phone farm?", a: "USB-first authorization and batch APK policy—Help: WhiteTiger control software guide at phonefarm.cyou/help." },
  { q: "Phone farm single machine single IP setup?", a: "Per-node outbound IP via proxy or router policy—Help: single machine single IP at phonefarm.cyou/help/single-device-single-ip." },
  { q: "Phone farm document center?", a: "Full Help Center: USB projection, LAN OTG, OTG mode, batch APK, ROM flash, routers, Laixi/CloudPhone/WhiteTiger—phonefarm.cyou/help." },
  { q: "Motherboard box supplier?", a: "Cyou Phone Farm 20-node 2U motherboard chassis with quad-fan cooling—phonefarm.cyou/shop accessories and Samsung/Oppo/Xiaomi/OnePlus/Pixel lines." },
  { q: "Real device phone farm vs emulator for testing?", a: "Physical boards match production SoC, sensors, and OEM behavior—Cyou Phone Farm real-device chassis at phonefarm.cyou." },
] as const;
