/** Help articles aligned with reference document center (Cyou Phone Farm wording). */
export const HELP_REFERENCE_ARTICLES = [
  {
    slug: "soft-router-user-guide",
    category: "network",
    title: "Soft Router User Documentation",
    excerpt: "Route farm subnets, DHCP pools, and egress policies for device labs.",
    body: `Soft routers (ikuai-class, OpenWrt, or enterprise gateway appliances) segment phone farm VLANs from office LANs. Cyou Phone Farm documents recommended DHCP pools, per-port isolation, and static routes before large LAN OTG scans. Reserve gateway IPs for control PCs and document MAC bindings for long-running test nodes.`,
  },
  {
    slug: "ikuai-dhcp-pool-limits",
    category: "network",
    title: "Router DHCP Pool & Default Connection Limits",
    excerpt: "Expand pools and connection caps for 20–200 node farms.",
    body: `Consumer routers default to small DHCP pools and low concurrent session limits. For phone farms, expand the pool to cover every node plus control PCs and spares. Raise connection quantity limits on ikuai and similar gateways. Split subnets when mixing USB-only phases with LAN mirroring. Cyou provides a network BOM review during Enterprise Deployment packages.`,
  },
  {
    slug: "ikuai-router-first-boot",
    category: "network",
    title: "Network Router First Boot Settings",
    excerpt: "Initial WAN/LAN, DHCP, and farm VLAN setup checklist.",
    body: `On first boot: set WAN uplink, define farm LAN subnet (e.g. 192.168.88.0/24), enable DHCP with adequate lease time, disable guest WiFi bleed into farm VLAN, and document DNS forwarders. Test one box on USB before enabling LAN scan across the full subnet.`,
  },
  {
    slug: "samsung-farm-official-rom-flash",
    category: "firmware",
    title: "Samsung Farm: Flash Official ROM / System Downgrade",
    excerpt: "When to stay on official builds vs optimized farm ROM.",
    body: `Official Samsung builds require ADB authorization files and may need USB-first OTG enablement. Downgrade only with factory-approved packages—document serial and ROM build before flashing. Cyou burn-in sheets list shipped ROM tier; do not mix unofficial images without support approval.`,
  },
  {
    slug: "samsung-farm-optimized-rom",
    category: "firmware",
    title: "Samsung Farm: Optimized Farm ROM Update",
    excerpt: "Faster LAN mirroring and reduced auth steps on farm-tuned images.",
    body: `Optimized farm ROM reduces first-connection steps for LAN OTG and batch APK workflows. Updates ship with Cyou chassis when agreed in the PO. Always flash matching partition packages; verify checksums and keep a rollback image per rack.`,
  },
  {
    slug: "huananzhi-x99-xhci-bios",
    category: "firmware",
    title: "Huananzhi X99 BIOS: Disable XHCI Handoff",
    excerpt: "Stabilize USB trees on legacy control PC motherboards.",
    body: `On Huananzhi X99 and similar boards driving many USB hubs, disable problematic XHCI handoff in BIOS when nodes drop during mirror sessions. Use rear motherboard ports or add-in USB controllers. Match PSU rating on the control PC when hubs exceed 60 ports.`,
  },
  {
    slug: "mirror-software-vip-overview",
    category: "control",
    title: "Control Software Setup Packages (VIP-style onboarding)",
    excerpt: "Remote workspace setup — not third-party license resale.",
    body: `Reference shops sell mirror tool CDKEYs; Cyou Phone Farm provides **configuration services** for customer-selected control software: USB mirroring baseline, LAN scan ranges, multi-monitor layout, operator accounts, and handover checklists. Licenses remain with the customer’s vendor accounts.`,
  },
  {
    slug: "control-software-types",
    category: "control",
    title: "Control Software Types (USB / LAN / Group Control)",
    excerpt: "Free and paid mirror stacks — we configure, you license.",
    body: `Common stacks include USB screen mirroring, LAN OTG projection, WiFi handoff, and group-control suites with sync tap and batch APK. We document topology for powered USB hubs, TCP 5555 enablement on official ROM, and segment scans on the farm subnet only.`,
  },
  {
    slug: "batch-file-image-transfer",
    category: "control",
    title: "Batch File & Image Transfer",
    excerpt: "Push assets to test groups without per-device manual copy.",
    body: `Use device groups to push images, documents, and config files. Test on one node before fleet push. Large files may require LAN path instead of USB when throughput matters.`,
  },
  {
    slug: "wallpaper-batch-set",
    category: "control",
    title: "Batch Wallpaper & Display Settings",
    excerpt: "Align home screens for visual QA and operator recognition.",
    body: `Batch wallpaper and DPI settings help operators spot offline tiles quickly. Apply to test groups after ROM verification; avoid changing display density during active regression windows.`,
  },
  {
    slug: "shared-device-mode",
    category: "control",
    title: "Shared Device / Multi-Operator Access",
    excerpt: "Permissions when several engineers share one control PC.",
    body: `Define master operator, read-only viewers, and group-scoped permissions. Document escalation to Cyou support when sync control conflicts appear across concurrent sessions.`,
  },
  {
    slug: "adb-keyboard-input",
    category: "control",
    title: "ADB Keyboard & Text Input",
    excerpt: "Install ADB keyboard for scripted text entry on farms.",
    body: `Some automation flows require ADB Keyboard or equivalent input methods. Install via batch APK on a canary node, validate locale and IME behavior, then roll to fleet groups.`,
  },
  {
    slug: "usb-power-management",
    category: "troubleshooting",
    title: "USB Power Management & Hub Sizing",
    excerpt: "Avoid selective suspend and undersized hubs.",
    body: `Disable USB selective suspend on control PCs. Size powered hubs for continuous mirror load—consumer bus-powered hubs fail under 16+ active nodes. Log hub model and port map in your asset register.`,
  },
  {
    slug: "equipment-detection-failures",
    category: "troubleshooting",
    title: "Equipment Detection Failures",
    excerpt: "Systematic recovery when nodes disappear from the panel.",
    body: `Re-seat uplink cable, swap hub port, verify data-rated cable, compare serial to burn-in sheet, restart mirror service, and isolate node from production groups until root cause is logged.`,
  },
  {
    slug: "cloud-phone-hybrid-note",
    category: "getting-started",
    title: "Real Device Farm vs Cloud Phone (Hybrid Note)",
    excerpt: "When to keep real hardware vs add cloud seats.",
    body: `Real motherboard farms provide authentic SoC, sensors, and storage. Cloud phones add elastic seats but differ in fingerprint and network path. Many enterprises run real farms for release QA and optional cloud bridges for burst capacity—we document hybrid topology when requested.`,
  },
] as const;

export const FAQ_REFERENCE_ADDITIONS = [
  { q: "What is USB screen projection?", a: "USB mirroring connects each farm box to the control PC through powered USB hubs—lowest latency path and required for first authorization on official ROM builds." },
  { q: "What is LAN OTG projection?", a: "After USB setup, nodes can mirror over the LAN using OTG TCP (port 5555 on official builds). Control PC and farm must share one router subnet." },
  { q: "What is USB to WiFi handoff?", a: "Switch a connected device from USB to WiFi/LAN mode in the mirror tool to free cables—use sparingly on large walls; routers handle ~5–10 mirrors per AP on consumer gear." },
  { q: "How does sync control work?", a: "One master window drives tap/swipe on all selected nodes in a group. Use test groups before production regression." },
  { q: "How do I batch install APK?", a: "Select devices → batch install → choose APK. Test one node for split/incompatible APKs before fleet push." },
  { q: "What is ADB authorization on official ROM?", a: "Official Android builds require ADB key files on the control PC. Cyou Remote Control Configuration covers placement and renewal." },
  { q: "What is optimized farm ROM?", a: "Farm-tuned images reduce LAN scan and auth steps. ROM tier is listed on your burn-in sheet—do not flash unknown packages." },
  { q: "How do I set single machine single IP?", a: "Use router policies, proxies, or VLAN egress per test group. We help document topology during enterprise quotes—not legal advice on platform rules." },
  { q: "What is Mirror Software VIP-style setup?", a: "We offer onboarding packages for your licensed mirror workspace—multi-monitor layout, LAN ranges, accounts—not resale of third-party CDKEYs." },
  { q: "Which control software do you support?", a: "Industry mirror and group-control tools (USB, LAN OTG, WiFi handoff). We configure customer-chosen stacks; licenses stay with the customer." },
  { q: "Do you sell Laixi / CloudPhone / WhiteTiger licenses?", a: "No—we configure environments for tools you license separately unless explicitly agreed in writing." },
  { q: "How to connect OTG mode?", a: "See Help: Tutorial on connecting phone farm in OTG mode—USB first, enable TCP 5555, then LAN scan on farm subnet." },
  { q: "Recommended network for 40+ nodes?", a: "Dedicated gigabit switch per rack, expanded DHCP, AP limits for WiFi mirrors, documented VLANs—see Large Farm Network Deployment article." },
  { q: "Samsung S8/S9/S10 farm specs?", a: "Shop lists CPU, RAM, Android version per SKU. Reference prices in USD; bulk MOQ confirmed by sales." },
  { q: "How do I order from the homepage?", a: "Request Quote or WhatsApp Sales for any SKU. Standard hardware may also support direct online checkout when sales enables it—enterprise and custom mixes always go through quotation first." },
  { q: "How are online orders confirmed?", a: "Sales confirms proforma invoice, MOQ, and payment instructions before you pay. Order status updates after payment is verified by our team." },
  { q: "Do you offer group control onboarding?", a: "Yes—Group Control Onboarding service covers sync baseline, batch APK policy, and operator handover." },
  { q: "Annual maintenance?", a: "Annual Maintenance Support includes quarterly health review, fan/PSU guidance, and control-stack update planning." },
  { q: "Is there a video connection guide?", a: "Help Center includes Device Connection Video Guide and step articles for USB, LAN, and WiFi paths." },
  { q: "Global shipping regions?", a: "We regularly export to US, UK, EU, Mexico, Russia, Southeast Asia, Middle East, and more from Guangzhou." },
] as const;
