/** Help articles aligned with reference document center (Cyou Phone Farm wording). */
export const HELP_REFERENCE_ARTICLES = [
  {
    slug: "soft-router-user-guide",
    category: "network",
    title: "Soft Router User Documentation",
    excerpt: "Route farm subnets, DHCP pools, and egress policies for device labs.",
    body: `Soft routers (ikuai-class, OpenWrt, or enterprise gateway appliances) segment phone farm VLANs from office LANs. Cyou Phone Farm documents recommended DHCP pools, per-port isolation, and static routes before large LAN OTG scans. Reserve gateway IPs for control PCs and document MAC bindings for long-running test nodes.`,
  },
  {
    slug: "ikuai-dhcp-pool-limits",
    category: "network",
    title: "Router DHCP Pool & Default Connection Limits",
    excerpt: "Expand pools and connection caps for 20–200 node farms.",
    body: `Consumer routers default to small DHCP pools and low concurrent session limits. For phone farms, expand the pool to cover every node plus control PCs and spares. Raise connection quantity limits on ikuai and similar gateways. Split subnets when mixing USB-only phases with LAN mirroring. Cyou provides a network BOM review during Enterprise Deployment packages.`,
  },
  {
    slug: "ikuai-router-first-boot",
    category: "network",
    title: "Network Router First Boot Settings",
    excerpt: "Initial WAN/LAN, DHCP, and farm VLAN setup checklist.",
    body: `On first boot: set WAN uplink, define farm LAN subnet (e.g. 192.168.88.0/24), enable DHCP with adequate lease time, disable guest WiFi bleed into farm VLAN, and document DNS forwarders. Test one box on USB before enabling LAN scan across the full subnet.`,
  },
  {
    slug: "samsung-farm-official-rom-flash",
    category: "firmware",
    title: "Samsung Farm: Flash Official ROM / System Downgrade",
    excerpt: "When to stay on official builds vs optimized farm ROM.",
    body: `Official Samsung builds require ADB authorization files and may need USB-first OTG enablement. Downgrade only with factory-approved packages—document serial and ROM build before flashing. Cyou burn-in sheets list shipped ROM tier; do not mix unofficial images without support approval.`,
  },
  {
    slug: "samsung-farm-optimized-rom",
    category: "firmware",
    title: "Samsung Farm: Optimized Farm ROM Update",
    excerpt: "Faster LAN mirroring and reduced auth steps on farm-tuned images.",
    body: `Optimized farm ROM reduces first-connection steps for LAN OTG and batch APK workflows. Updates ship with Cyou chassis when agreed in the PO. Always flash matching partition packages; verify checksums and keep a rollback image per rack.`,
  },
  {
    slug: "huananzhi-x99-xhci-bios",
    category: "firmware",
    title: "Huananzhi X99 BIOS: Disable XHCI Handoff",
    excerpt: "Stabilize USB trees on legacy control PC motherboards.",
    body: `On Huananzhi X99 and similar boards driving many USB hubs, disable problematic XHCI handoff in BIOS when nodes drop during mirror sessions. Use rear motherboard ports or add-in USB controllers. Match PSU rating on the control PC when hubs exceed 60 ports.`,
  },
  {
    slug: "mirror-software-vip-overview",
    category: "control",
    title: "Control Software Setup Packages (VIP-style onboarding)",
    excerpt: "Remote workspace setup — not third-party license resale.",
    body: `Reference shops sell mirror tool CDKEYs; Cyou Phone Farm provides **configuration services** for customer-selected control software: USB mirroring baseline, LAN scan ranges, multi-monitor layout, operator accounts, and handover checklists. Licenses remain with the customer’s vendor accounts.`,
  },
  {
    slug: "control-software-types",
    category: "control",
    title: "Control Software Types (USB / LAN / Group Control)",
    excerpt: "Free and paid mirror stacks — we configure, you license.",
    body: `Common stacks include USB screen mirroring, LAN OTG projection, WiFi handoff, and group-control suites with sync tap and batch APK. We document topology for powered USB hubs, TCP 5555 enablement on official ROM, and segment scans on the farm subnet only.`,
  },
  {
    slug: "batch-file-image-transfer",
    category: "control",
    title: "Batch File & Image Transfer",
    excerpt: "Push assets to test groups without per-device manual copy.",
    body: `Use device groups to push images, documents, and config files. Test on one node before fleet push. Large files may require LAN path instead of USB when throughput matters.`,
  },
  {
    slug: "wallpaper-batch-set",
    category: "control",
    title: "Batch Wallpaper & Display Settings",
    excerpt: "Align home screens for visual QA and operator recognition.",
    body: `Batch wallpaper and DPI settings help operators spot offline tiles quickly. Apply to test groups after ROM verification; avoid changing display density during active regression windows.`,
  },
  {
    slug: "shared-device-mode",
    category: "control",
    title: "Shared Device / Multi-Operator Access",
    excerpt: "Permissions when several engineers share one control PC.",
    body: `Define master operator, read-only viewers, and group-scoped permissions. Document escalation to Cyou support when sync control conflicts appear across concurrent sessions.`,
  },
  {
    slug: "adb-keyboard-input",
    category: "control",
    title: "ADB Keyboard & Text Input",
    excerpt: "Install ADB keyboard for scripted text entry on farms.",
    body: `Some automation flows require ADB Keyboard or equivalent input methods. Install via batch APK on a canary node, validate locale and IME behavior, then roll to fleet groups.`,
  },
  {
    slug: "usb-power-management",
    category: "troubleshooting",
    title: "USB Power Management & Hub Sizing",
    excerpt: "Avoid selective suspend and undersized hubs.",
    body: `Disable USB selective suspend on control PCs. Size powered hubs for continuous mirror load—consumer bus-powered hubs fail under 16+ active nodes. Log hub model and port map in your asset register.`,
  },
  {
    slug: "equipment-detection-failures",
    category: "troubleshooting",
    title: "Equipment Detection Failures",
    excerpt: "Systematic recovery when nodes disappear from the panel.",
    body: `Re-seat uplink cable, swap hub port, verify data-rated cable, compare serial to burn-in sheet, restart mirror service, and isolate node from production groups until root cause is logged.`,
  },
  {
    slug: "cloud-phone-hybrid-note",
    category: "getting-started",
    title: "Real Device Farm vs Cloud Phone (Hybrid Note)",
    excerpt: "When to keep real hardware vs add cloud seats.",
    body: `Real motherboard farms provide authentic SoC, sensors, and storage. Cloud phones add elastic seats but differ in fingerprint and network path. Many enterprises run real farms for release QA and optional cloud bridges for burst capacity—we document hybrid topology when requested.`,
  },
  {
    slug: "laixi-control-software-guide",
    category: "control",
    title: "Laixi Group Control Software Setup",
    excerpt: "Configure Laixi USB mirroring and group control on phone farm hardware.",
    body: `Laixi is an industry-leading Android screen projection and group-control suite. Cyou Phone Farm does not resell Laixi CDKEYs by default—we configure your licensed Laixi workspace on real-device chassis: powered USB hub mapping, ADB authorization on official ROM, LAN OTG scan ranges on the farm subnet, device groups, and operator handoff. See also Help: USB screen projection and OTG mode tutorial.`,
  },
  {
    slug: "cloudphone-control-software-guide",
    category: "control",
    title: "CloudPhone Screen Projection Setup",
    excerpt: "CloudPhone mirror workspace for cost-effective multi-device control.",
    body: `CloudPhone is a commonly recommended Android mirror tool with batch APK, sync control, and LAN mirroring. After you license CloudPhone, our Remote Control Configuration service maps each chassis node to the control PC, validates TCP 5555 on official builds, and documents batch install policy. For cloud-phone subscription workflows used alongside real hardware, see Help: Cloud phone subscription workflow.`,
  },
  {
    slug: "whitetiger-control-software-guide",
    category: "control",
    title: "WhiteTiger Mirror Software Setup",
    excerpt: "WhiteTiger / Panda-class mirror stacks on phone farms.",
    body: `WhiteTiger and related mirror tools are widely used for Android group control. We configure USB-first authorization, LAN discovery on the farm VLAN only, multi-monitor tiling, and spare operator accounts. Licenses remain on your vendor account—we provide setup services and Guangzhou hardware burn-in sheets that match your ROM tier.`,
  },
  {
    slug: "cloud-phone-subscription-workflow",
    category: "control",
    title: "Cloud Phone Subscription Workflow (Hybrid Labs)",
    excerpt: "Add cloud phone seats to a mirror tool alongside real farm nodes.",
    body: `Hybrid labs sometimes combine real motherboard farms with rented cloud phone seats in Laixi, CloudPhone, or similar tools. Typical workflow: purchase cloud seats from your vendor → copy subscription URL from vendor portal → add subscription in mirror software → validate screen projection on a canary node → document which workloads stay on real hardware vs cloud. Cyou Phone Farm focuses on real-device chassis; we document hybrid topology during enterprise quotes.`,
  },
  {
    slug: "buyer-specifications-logistics",
    category: "buying",
    title: "Buyer Specifications & Logistics",
    excerpt: "Dimensions, weight, power, voltage, models, control PC scale, lead time, packing, warranty, RMA, and pre-shipment photos.",
    body: `Standard 20-node 2U chassis reference: ~480×400×88 mm, ~14 kg bare / ~18–22 kg packed, 110–220 V adaptive PSU, typical 280–420 W draw at full load. See full tables for supported phone models, how many boxes one control PC manages, delivery time, export packing, remote setup, 90-day warranty, and RMA steps.`,
  },
] as const;

export const FAQ_REFERENCE_ADDITIONS = [
  { q: "What is USB screen projection?", a: "USB mirroring connects each farm box to the control PC through powered USB hubs—lowest latency path and required for first authorization on official ROM builds." },
  { q: "What is LAN OTG projection?", a: "After USB setup, nodes can mirror over the LAN using OTG TCP (port 5555 on official builds). Control PC and farm must share one router subnet." },
  { q: "What is USB to WiFi handoff?", a: "Switch a connected device from USB to WiFi/LAN mode in the mirror tool to free cables—use sparingly on large walls; routers handle ~5–10 mirrors per AP on consumer gear." },
  { q: "How does sync control work?", a: "One master window drives tap/swipe on all selected nodes in a group. Use test groups before production regression." },
  { q: "How do I batch install APK?", a: "Select devices → batch install → choose APK. Test one node for split/incompatible APKs before fleet push." },
  { q: "What is ADB authorization on official ROM?", a: "Official Android builds require ADB key files on the control PC. Cyou Remote Control Configuration covers placement and renewal." },
  { q: "What is optimized farm ROM?", a: "Farm-tuned images reduce LAN scan and auth steps. ROM tier is listed on your burn-in sheet—do not flash unknown packages." },
  { q: "How do device labs segment network egress?", a: "Use VLANs, router policies, and documented subnets per test group. We help map topology during enterprise quotes—your IT team owns compliance policy." },
  { q: "What is Mirror Software VIP-style setup?", a: "We offer onboarding packages for your licensed mirror workspace—multi-monitor layout, LAN ranges, accounts—not resale of third-party CDKEYs." },
  { q: "Which control software do you support?", a: "Industry mirror and group-control tools (USB, LAN OTG, WiFi handoff). We configure customer-chosen stacks; licenses stay with the customer." },
  { q: "Do you sell Laixi / CloudPhone / WhiteTiger licenses?", a: "No—we configure environments for tools you license separately unless explicitly agreed in writing." },
  { q: "How to connect OTG mode?", a: "See Help: Tutorial on connecting phone farm in OTG mode—USB first, enable TCP 5555, then LAN scan on farm subnet." },
  { q: "Recommended network for 40+ nodes?", a: "Dedicated gigabit switch per rack, expanded DHCP, AP limits for WiFi mirrors, documented VLANs—see Large Farm Network Deployment article." },
  { q: "Samsung S8/S9/S10 farm specs?", a: "Shop lists CPU, RAM, Android version per SKU. Reference prices in USD; bulk MOQ confirmed by sales." },
  { q: "How do I order from the homepage?", a: "Request Quote or WhatsApp Sales for any SKU. Standard hardware may also support direct online checkout when sales enables it—enterprise and custom mixes always go through quotation first." },
  { q: "How are online orders confirmed?", a: "Sales confirms proforma invoice, MOQ, and payment instructions before you pay. Order status updates after payment is verified by our team." },
  { q: "Do you offer group control onboarding?", a: "Yes—Group Control Onboarding service covers sync baseline, batch APK policy, and operator handover." },
  { q: "Annual maintenance?", a: "Annual Maintenance Support includes quarterly health review, fan/PSU guidance, and control-stack update planning." },
  { q: "Is there a video connection guide?", a: "Help Center includes Device Connection Video Guide and step articles for USB, LAN, and WiFi paths." },
  { q: "Global shipping regions?", a: "We regularly export to US, UK, EU, Mexico, Russia, Southeast Asia, Middle East, and more from Guangzhou." },
  { q: "Phone farm box dimensions and weight?", a: "Standard 20-node 2U chassis: approx. 480×400×88 mm, ~14 kg bare, ~18–22 kg packed. Details: Help buyer specifications & logistics." },
  { q: "Phone farm box power consumption and voltage?", a: "Typical 280–420 W at full 20-node load; 450–550 W adaptive PSU, 110–220 V AC 50/60 Hz. Region plug quoted per destination." },
  { q: "How many phone farm boxes per control PC?", a: "USB mirroring: usually 1 box (20 nodes) per USB controller; ~2 boxes with dual controller cards. LAN OTG scales further on same VLAN — see Help buyer specifications." },
  { q: "Pre-shipment photos before export?", a: "Yes on request — chassis, burn-in sheet, and packed carton photos/video before sealing. Ask sales in quotation or contact form." },
  { q: "What if a phone farm node is defective?", a: "Message support with burn-in serial and photos. 90-day warranty for manufacturing faults; spare parts from Guangzhou. Transit damage: report within 7 days." },
  { q: "Remote installation available?", a: "Yes — baseline guides with hardware; Remote Control Configuration and service packages include screenshare setup. See /services/packages." },
] as const;
